config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :trades, only: [:show, :new, :create]
  resources :subsectors, only: [:index, :show, :new, :create]
  resources :planets, only: [:index, :show]

  get '/about', to: 'about#show'
  root 'trades#new'
end

app/models/subsector.rb
class Subsector < ApplicationRecord
  has_many :planets, dependent: :destroy

  after_create :import_uwp

  def import_uwp
    #TODO: Iterate over data in uwp and extract trade codes, building the planets
    uwp.split("\n").each do |line|
      next unless line.match(Planet::REGEX)
      name = line.match(Planet::REGEX)[1]
      self.planets.create!(name: name.strip, uwp: line.strip)
    end
  end
end

app/controllers/subsectors_controller.rb
class SubsectorsController < ApplicationController
  helper_method :sort_column, :sort_direction

  def index
    @subsectors = Subsector.all
  end

  def show
    @subsector = Subsector.find(params[:id])
    @planets = @subsector.planets.order(sort_column + ' ' + sort_direction)
  end

  def new
    @subsector = Subsector.new
  end

  def create
    @subsector = Subsector.new(sanitized_params(params[:subsector]))
    if @subsector.save
      redirect_to subsectors_path, notice: "Subsector #{@subsector.name} successfully created!"
    else
      render :new, error: "Subsector creation failed, recheck your text formatting"
    end
  end

  private

  def sanitized_params(params)
    params.permit(:name, :uwp, :description)
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ?  params[:direction] : "asc"
  end

  def sort_column
    Planet.column_names.include?(params[:sort]) ? params[:sort] : "name"
  end
end

app/helpers/subsectors_helper.rb
module SubsectorsHelper
end

app/views/subsectors/_form.html.erb
<%= form_for @subsector, method: :post do |f| %>
  <div class="form-group row">
    <label for="subsector_name" class="col-sm-1 col-form-label">Name:</label>
    <div class="col-sm-11">
      <%= f.text_field :name, size: 40, class: 'form-control' -%>
    </div>
  </div>
  <div class="form-group row">
    <label for="subsector_description" class="col-sm-1 col-form-label">Description:</label>
    <div class="col-sm-11">
      <%= f.text_area :description, cols: 60, rows: 10, class: 'form-control' -%>
    </div>
  </div>
  <div class="form-group row">
    <label for="subsector_uwp" class="col-sm-1 col-form-label">UWP:</label>
    <div class="col-sm-11">
      <%= f.text_area :uwp, cols: 60, rows: 20, class: 'form-control' -%>
    </div>
  </div>

  <%= f.submit 'Create Subsector', class: 'btn btn-primary' %>
<% end %>

app/views/subsectors/index.html.erb
<table class="table table-bordered table-condensed table-striped table-hover">
  <tr class="table-header">
    <th>Subsector Name</th>
    <th>Planets</th>
  </tr>
  <% @subsectors.each do |subsector| %>
    <tr>
      <td>
        <%= link_to subsector.name, subsector_path(subsector) %>
      </td>
      <td>
        <%= subsector.planets.count %>
      </td>
    </tr>
  <% end %>
</table>

app/views/subsectors/new.html.erb
<p>
  The format of the UWP is fairly specific. Due to the many variations that have existed
  over the decades, I've had to settle for one and make it work as well as I could.
  Any line that doesn't match a very specific regular expression is ignored, so if you
  notice planets missing from the subsector, this is probably why.
</p>
<p>
  This is an acceptable format, and works correctly:
  <pre>
    Zobabara   0101  C211000-0       P   Ba IC
    Zitue      0201  B471699-7      ST   NI A
    Nxen       0202  C757000-0      RT   Ba Ga
    Viena      0208  C88898A-4           Ga Hi Lt A
    Para       0301  E526000-0           Ba
    Tatee      0302  D7A4000-0       S   Ba Fl A
    Timaziezo  0304  B352136-7     NTC   Lo Po
    Fatatozi   0305  C654415-7           Ga NI
    Re         0306  C792527-8       T   NI
    Rirarinae  0307  B610300-12  NSTCP   Ht Lo R
    Batote     0308  C000447-10     SR   As NI Va
                     ||||||| |
    Ag Agricultural  ||||||| |           In Industrial
    As Asteroid      ||||||| +- Tech     Lo Low Population
    Ba Barren        ||||||+- Law        Lt Low Technology
    De Desert        |||||+- Government  Na Non-Agricultural
    Fl Fluid Oceans  ||||+- Population   NI Non-Industrial
    Ga Garden        |||+- Hydro         Po Poor
    HiHighPopulation ||+- Atmosphere     Ri Rich
    HtHighTechnology |+- Size            Wa Water World
    IC Ice-Capped    +- Starport         Va Vacuum
  </pre>
</p>

<%= render partial: 'form' %>

app/views/subsectors/show.html.erb
<div class="row">
  <div class="col-sm-12">
    <p>
      Physical Stats follow this format:<br />
      Starport Size Atmosphere Hydro Population Government Law - Tech
    </p>
    <strong>Trade Codes:</strong><br />
    <div class="col-sm-4">
      <p>
        Ag Agricultural<br />
        As Asteroid<br />
        Ba Barren<br />
        De Desert<br />
        Fl Fluid Oceans<br />
        Ga Garden
      </p>
    </div>
    <div class="col-sm-4">
      <p>
        Hi High Population<br />
        Ht High Technology<br />
        IC Ice-Capped<br />
        In Industrial<br />
        Lo Low Population<br />
        Lt Low Technology
      </p>
    </div>
    <div class="col-sm-4">
      <p>
        Na Non-Agricultural<br />
        NI Non-Industrial<br />
        Po Poor<br />
        Ri Rich<br />
        Wa Water World<br />
        Va Vacuum
      </p>
    </div>
    <p>
      <strong>Bases:</strong> (N)aval – (S)cout – (R)esearch – (T)AS – (C)onsulate – (P)irate
    </p>
    <p>
      Row <strong>color</strong> is determined by the travel code. Light yellow for Amber,
      and light red for Red travel zones.
    </p>
    <p>
      <strong>Stats:</strong> starport size atmosphere hydro population government law - Tech
    </p>

    <p>
      <%= "<strong>Description:</strong>".html_safe + " #{@subsector.description}" unless @subsector.description.blank? -%>
    </p>
  </div>
</div>
<table class="table table-bordered table-condensed table-striped table-hover">
  <tr class="table-header">
    <th><%= sortable "name" %></th>
    <th><%= sortable "hex" %></th>
    <th>Stats</th>
    <th>Base Code(s)</th>
    <th>Trade Codes</th>
  </tr>
  <% @planets.each do |planet| %>
    <tr class="<%= travel_code_class(planet) -%>">
      <td>
        <%= link_to planet.name, planet_path(planet) %>
      </td>
      <td>
        <%= planet.hex %>
      </td>
      <td>
        <%= planet.physical_stats %>
      </td>
      <td>
        <%= planet.base_code %>
      </td>
      <td>
        <%= planet.trade_codes %>
      </td>
    </tr>
  <% end %>
</table>