config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :trades, only: [:show, :new, :create]
  resources :subsectors, only: [:index, :show, :new, :create]
  resources :planets, only: [:index, :show]

  get '/about', to: 'about#show'
  root 'trades#new'
end

app/models/planet.rb
class Planet < ApplicationRecord
  REGEX = Regexp.new(/\A\s*(\w+)\s+(\d{4})\s+([ABCDEX]\w{6}-\w{1,2})\s*([NSTRCP]{0,5})\s*((?:\w{2}\s*){0,5})\s*([GAR])?\s*\z/)
  belongs_to :subsector, touch: true
  has_many :supplier_deals

  validates_format_of :uwp, with: REGEX

  before_save :set_hex

  def trade_codes
    begin
      return self.uwp.match(REGEX)[5].strip.titleize
    rescue
      return ''
    end
  end

  def travel_code
    begin
      return self.uwp.match(REGEX)[6].strip.titleize
    rescue
      return 'G'
    end
  end

  def base_code
    begin
      return self.uwp.match(REGEX)[4].strip
    rescue
      return ''
    end
  end

  def star_port
    self.physical_stats[0] || ''
  end

  def refigure_hex
    begin
      return self.uwp.match(REGEX)[2].strip
    rescue
      return ''
    end
  end

  def physical_stats
    begin
      return self.uwp.match(REGEX)[3].strip
    rescue
      return ''
    end
  end

  def tech
    begin
      return physical_stats[8..9]
    rescue
      return ''
    end
  end

  def law
    begin
      return physical_stats[6]
    rescue
      return ''
    end
  end

  def government
    begin
      return physical_stats[5]
    rescue
      return ''
    end
  end

  def population
    begin
      return physical_stats[4]
    rescue
      return ''
    end
  end

  def hydro
    begin
      return physical_stats[3]
    rescue
      return ''
    end
  end

  def atmosphere
    begin
      return physical_stats[2]
    rescue
      return ''
    end
  end

  def size
    begin
      return physical_stats[1]
    rescue
      return ''
    end
  end

  private

  def set_hex
    self.hex = self.refigure_hex if self.hex.blank?
  end
end

app/controllers/planets_controller.rb
class PlanetsController < ApplicationController

  def show
    @planet = Planet.find(params[:id])
  end
end

app/helpers/planets_helper.rb
module PlanetsHelper
  def technology_description(tech_code)
    case tech_code.to_s
    when "0"
      return "(Primitive) No technology. TL 0 species have only discovered
the simplest tools and principles, and are on a par with Earth’s
Stone Age."
    when "1"
      return "(Primitive) Roughly on a par with Bronze or Iron age technology.
TL 1 science is mostly superstition, but they can manufacture
weapons and work metals."
    when "2"
      return "(Primitive) Renaissance technology. TL 2 brings with it a
greater understanding of chemistry, physics, biology and astronomy
as well as the scientifi c method."
    when "3"
      return "(Primitive) The advances of TL 2 are now applied, bringing the
germ of industrial revolution and steam power. Primitive fi rearms
now dominate the battlefield. This is roughly comparable to the
early 19th century."
    when "4"
      return "(Industrial) The transition to industrial revolution is complete,
bringing plastics, radio and other such inventions. Roughly
comparable to the late 19th/early 20th century."
    when "5"
      return "(Industrial) TL 5 brings widespread electrification, telecommunications
and internal combustion. At the high end of the
TL, atomics and primitive computing appear. Roughly on a par with
the mid–20th century."
    when "6"
      return "(Industrial) TL 6 brings the development of fission power and
more advanced computing. Advances in materials technology and
rocketry bring about the dawn of the space age."
    when "7"
      return "(Pre-Stellar) A pre-stellar society can reach orbit reliably and
has telecommunications satellites. Computers become common.
At the time of writing, humanity is currently somewhere between
TL 7 and TL 8."
    when "8"
      return "(Pre-Stellar) At TL 8, it is possible to reach other worlds in
the same system, although terraforming or full colonisation are not
within the culture’s capacity. Permanent space habitats become
possible. Fusion power becomes commercially viable."
    when "9"
      return "(Pre-Stellar) The defi ning element of TL 9 is the development
of gravity manipulation, which makes space travel vastly safer
and faster. This research leads to development of the Jump drive,
which occurs near the end of this Tech Level. TL 9 cultures can
colonise other worlds, although going to a colony is generally
a one-way trip."
    when "10"
      return "(Early Stellar) With the advent of Jump, nearby systems
are opened up. Orbital habitats and factories become common.
Interstellar travel and trade lead to an economic boom. Colonies
become much more viable."
    when "11"
      return "(Early Stellar) The fi rst true artifi cial intelligences become
possible, as computers are able to model synaptic networks. Gravsupported
structures reach to the heavens. Jump–2 travel becomes
possible, allowing easier travel beyond the one-Jump stellar mains."
    when "12"
      return "(Average Stellar) Weather control revolutionises terraforming
and agriculture. Man-portable plasma weapons and carrier-mounted
fusion guns make the battlefield untenable for unarmoured
combatants. Jump–3 travel is developed."
    when "13"
      return "(Average Stellar) The battle dress appears on the battlefi eld
in response to the new weapons. Cloning of body parts becomes
easy. Advances in hull design and thruster plates means that
spacecraft can easily enter atmosphere and even go underwater.
Jump–4 travel."
    when "14"
      return "(Average Stellar) Fusion weapons become man-portable.
Flying cities appear. Jump–5 travel."
    when "15"
      return "(High Stellar) Black globe generators suggest a new direction
for defensive technologies, while the development of synthetic
anagathics means that the human lifespan is now vastly increased.
Jump–6 travel."
    end
  end

  def government_description(government)
    case government.to_s
    when "0"
      return "None No government structure. In many cases,
      family bonds predominate.
      Family, Clan,
      Anarchy.
      Common
      Contraband: None"
    when "1"
      return "Company/corporation Ruling functions are assumed by a company
      managerial elite, and most citizenry are
      company employees or dependants.
      Corporate outpost,
      asteroid mine,
      feudal domain.
      Common
      Contraband: Weapons, Drugs,
      Travellers"
    when "2"
      return "Participating democracy Ruling functions are reached by the advice and
      consent of the citizenry directly.
      Collective, tribal
      council, commlinked
      consensus
      Common
      Contraband: Drugs"
    when "3"
      return "Self-perpetuating oligarchy Ruling functions are performed by a restricted
      minority, with little or no input from the mass
      of citizenry.
      Plutocracy,
      hereditary ruling
      caste.
      Common
      Contraband: Technology,
      Weapons,
      Travellers"
    when "4"
      return "Representative democracy Ruling functions are performed by elected
      representatives.
      Republic,
      democracy.
      Common
      Contraband: Drugs, Weapons,
      Psionics."
    when "5"
      return "Feudal technocracy Ruling functions are performed by specifi c
      individuals for persons who agree to be ruled
      by them. Relationships are based on the
      performance of technical activities which are
      mutually beneficial.
      Common
      Contraband: Technology,
      Weapons,
      Computers"
    when "6"
      return "Captive government Ruling functions are performed by an imposed
      leadership answerable to an outside group.
      A colony or
      conquered area.
      Common
      Contraband: Weapons,
      Technology,
      Travellers"
    when "7"
      return "Balkanisation No central authority exists; rival governments
      complete for control. Law level refers to the
      government nearest the starport.
      Multiple
      governments,
      civil war.
      Common
      Contraband: Varies"
    when "8"
      return "Civil service bureaucracy Ruling functions are performed by government
      agencies employing individuals selected for
      their expertise.
      Technocracy,
      Communism.
      Common
      Contraband: Drugs, Weapons"
    when "9"
      return "Impersonal Bureaucracy Ruling functions are performed by agencies
      which have become insulated from the
      governed citizens.
      Entrenched castes
      of bureaucrats,
      decaying empire.
      Common
      Contraband: Technology,
      Weapons, Drugs,
      Travellers, Psionics"
    when "A"
      return "Charismatic dictator Ruling functions are performed by agencies
      directed by a single leader who enjoys the
      overwhelming confi dence of the citizens.
      Revolutionary
      leader, messiah,
      emperor.
      Common
      Contraband: None"
    when "B"
      return "Non-charismatic leader A previous charismatic dictator has been
      replaced by a leader through normal channels.
      Military
      dictatorship,
      hereditary
      kingship.
      Common
      Contraband: Weapons,
      Technology,
      Computers"
    when "C"
      return "Charismatic oligarchy Ruling functions are performed by a select
      group of members of an organisation or class
      which enjoys the overwhelming confi dence of
      the citizenry.
      Junta,
      revolutionary
      council.
      Common
      Contraband: Weapons"
    when "D"
      return "Religious dictatorship Ruling functions are performed by a religious
      organisation without regard to the specifi c
      individual needs of the citizenry.
      Cult, transcendent
      philosophy, psionic
      group mind.
      Common
      Contraband: Varies"
    end
  end

  def population_description(population)
    case population.to_s
    when "0"
      return "0"
    when "1"
      return "Few 1+ A tiny farmstead or a single family"
    when "2"
      return "Hundreds 100+ A village"
    when "3"
      return "Thousands 1,000+"
    when "4"
      return "Tens of thousands 10,000+ Small town"
    when "5"
      return "Hundreds of thousands 100,000+ Average city"
    when "6"
      return "Millions 1,000,000+"
    when "7"
      return "Tens of millions 10,000,000+ Large city"
    when "8"
      return "Hundreds of millions 100,000,000+"
    when "9"
      return "Billions 1,000,000,000+ Present day Earth"
    when "A"
      return "Tens of billions 10,000,000,000+"
    when "B"
      return "Hundreds of billions 100,000,000,000+ Incredibly crowded world"
    when "C"
      return "Trillions 1,000,000,000,000+ World-city"
    end
  end

  def hydro_description(hydro)
    hydro = 10 if hydro == 'A'
    return "#{hydro.to_i * 10}% surface liquid."
  end

  def starport_description(star_port)
    case star_port.to_s
    when "A"
      return "Excellent, berthing: 1d6x1000Cr, Refined fuel, Shipyard (all) Repairs"
    when "B"
      return "Good, berthing: 1d6x500Cr, Refined fuel, Shipyard (Spacecraft) Repairs"
    when "C"
      return "Routine, berthing: 1d6x100Cr, Refined fuel, Shipyard (small craft) Repairs"
    when "D"
      return "Poor, berthing: 1d6x10Cr, Unrefined fuel, Limited Repairs"
    when "E"
      return "Frontier, berthing: 0, Unrefined fuel, No Repairs"
    when "X"
      return "None, berthing: 0Cr, no fuel, No Repairs"
    end
  end

  def travel_code_description(travel_code)
    case travel_code.to_s
    when "A"
      return "Amber. An Amber world has
been deemed dangerous by the Imperium, and travellers are warned
to be on their guard. Amber worlds are often undergoing upheaval
or revolution, or else are naturally hazardous environments."
    when "G"
      return "Green, no restrictions"
    when "R"
      return "Red, worlds like this are interdicted and travel to them is forbidden. A world
might be Red because the Imperium wishes to preserve it, or
because the world is too dangerous to allow visitors. Interdictions
are enforced by the Imperial Navy."

app/views/planets/show.html.erb
<h1><%= @planet.name -%></h1>
<div class="row">
  <div class="col-sm-12">
    <p>
      Here you can generate the Trade Goods available today at a given supplier.
      Select their morality and click generate.
      <%= form_tag trades_path, method: :post, class: "navbar-form navbar-left search-form" do %>
        <%= check_box_tag "morally_ambiguous", true, false, :name => "morally_ambiguous" -%>
        Morally Ambiguous
        <%= hidden_field_tag "trade_codes[]", @planet.trade_codes  %>
        <%= hidden_field_tag "planet_id", @planet.id  %>
        </ul>
        <%= submit_tag("What's for sale today?", class: 'btn btn-primary') %>
      <% end %>
    </p>
    <p>
      <%= @planet.description %>
    </p>
    <table class="table table-bordered table-condensed table-striped table-hover">
      <tr class="table-header">
        <th>Hex</th>
        <th>Starport</th>
        <th>Size</th>
        <th>Atmosphere</th>
        <th>Hydro</th>
        <th>Population</th>
        <th>Government</th>
        <th>Law</th>
        <th>Tech</th>
        <th>Base(s)</th>
        <th>Trade</th>
      </tr>
      <tr class="<%= travel_code_class(@planet) -%>">
        <td>
          <%= @planet.hex %>
        </td>
        <td>
          <%= @planet.star_port %>
        </td>
        <td>
          <%= @planet.size %>
        </td>
        <td>
          <%= @planet.atmosphere %>
        </td>
        <td>
          <%= @planet.hydro %>
        </td>
        <td>
          <%= @planet.population %>
        </td>
        <td>
          <%= @planet.government %>
        </td>
        <td>
          <%= @planet.law %>
        </td>
        <td>
          <%= @planet.tech %>
        </td>
        <td>
          <%= @planet.base_code %>
        </td>
        <td>
          <%= @planet.trade_codes %>
        </td>
      </tr>
    </table>
  </div>
</div>
<div class="row">
  <div class="col-sm-4">
    <p class="text-justify">
      <strong>Technology:</strong>
      <%= technology_description(@planet.tech) -%>
    </p>
  </div>
  <div class="col-sm-4">
    <p class="text-justify">
      <strong>Star Port:</strong>
      <%= starport_description(@planet.star_port) -%>
    </p>
  </div>
  <div class="col-sm-4">
    <p class="text-justify">
      <strong>Government:</strong>
      <%= government_description(@planet.government) -%>
    </p>
  </div>
  <div class="col-sm-4">
    <p class="text-justify">
      <strong>Hydro:</strong>
      <%= hydro_description(@planet.hydro) -%>
    </p>
  </div>
  <div class="col-sm-4">
    <p class="text-justify">
      <strong>Population:</strong>
      <%= population_description(@planet.population) -%>
    </p>
  </div>
  <div class="col-sm-4">
    <p class="text-justify">
      <strong>Law:</strong>
      <%= law_description(@planet.law) -%>
    </p>
  </div>
  <div class="col-sm-4">
    <p class="text-justify">
      <strong>Bases:</strong>
      <%= bases_description(@planet.base_code) -%>
    </p>
  </div>
  <div class="col-sm-4">
    <p class="text-justify">
      <strong>Travel Code:</strong>
      <%= travel_code_description(@planet.travel_code) -%>
    </p>
  </div>
  <div class="col-sm-4">
    <p class="text-justify">
      <strong>Size:</strong>
      <%= size_description(@planet.size) -%>
    </p>
  </div>
  <div class="col-sm-4">
    <p class="text-justify">
      <strong>Atmosphere:</strong>
      <%= atmosphere_description(@planet.atmosphere) -%>
    </p>
  </div>
</div>